apiVersion: v1
kind: Service
metadata:
  name: basicweb-service
spec:
  type: NodePort # 외부에서 직접 IP를 입력해서 접속할 수 있도록 NodePort 타입으로 만들기
  selector:
    app: basicweb
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000 # 브라우저에서 접속시 30000번 포트로 접속하도록 설정
